//
// ResponseOperatorProductSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseOperatorProductSettings: Codable, JSONEncodable, Hashable {

    /** MaxQuantity is the maximum quantity of product that can be sold in one single purchase */
    public var maxQuantity: Int64?

    public init(maxQuantity: Int64? = nil) {
        self.maxQuantity = maxQuantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maxQuantity = "max_quantity"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maxQuantity, forKey: .maxQuantity)
    }
}

