//
// ResponseOperatorZone.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseOperatorZone: Codable, JSONEncodable, Hashable {

    /** ID is a unique identifier for the Zone */
    public var id: String?
    /** Resources contains a map with localizations */
    public var resources: [String: [String: String]]?
    /** Sort holds the sort order */
    public var sort: Int64?

    public init(id: String? = nil, resources: [String: [String: String]]? = nil, sort: Int64? = nil) {
        self.id = id
        self.resources = resources
        self.sort = sort
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case resources
        case sort
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(resources, forKey: .resources)
        try container.encodeIfPresent(sort, forKey: .sort)
    }
}

